### ISSUE TITLE
Compilation problem in windows environment

### ISSUE THREAD

**Issue by JianlayWang** [HTDerekLiu/intrinsic-simplification#1]
I configure the code based on CLion, and the operating system is windows, but there are some problems with the code during the build process. I want to know how your code should be configured in the windows environment.

![image](https://github.com/HTDerekLiu/intrinsic-simplification/assets/138512306/a6030db8-ee25-4f6f-8a75-5c8729f70388)

![image](https://github.com/HTDerekLiu/intrinsic-simplification/assets/138512306/112f7c40-5641-4fa7-89a0-b930e3c87ef9)

**Comment by MarkGillespie** [comment]
Thanks for pointing this out! I just pushed some changes and it seems to build properly for me on Windows now. Does the newest version of the code work on your machine?

**Comment by JianlayWang** [comment]
Thank you for your reply, the updated code is now able to run on my computer.
