### ISSUE TITLE
How to use only Gaussian curvature for iteration?

### ISSUE THREAD

**Issue by sonukiller** [HTDerekLiu/intrinsic-simplification#10]
I wanted to know if we can only use absolute Gaussian curvature to remove the vertex.

**Comment by HTDerekLiu** [comment]
You could. That would be closer (but still different) from the memoryless version of our method. More details can be found here https://www.cs.wm.edu/~ppeers/publications/Shoemaker2023IMS/Shoemaker_ARXIV2023.pdf

**Comment by sonukiller** [comment]
Thank you for sharing the IMS paper, actually I was looking into that. Do you know what changes can be made in the transportation cast for this?

**Comment by HTDerekLiu** [comment]
This should be easy, you just need to compute `cost` using the element wise summation of Gaussian curvature difference `dK` in [here](https://github.com/HTDerekLiu/intrinsic-simplification/blob/708bc7c77955f654d56292e4e7683d16caabfb5d/src/flatten_interior_vertex_and_cost.cpp#L163). 
This will ignore the transport and solely focus on the difference in Gaussian curvatures.

You would need to do the same change for the following functions
- `pre_flatten_interior_vertex_and_cost`
- `flatten_interior_vertex_and_cost`
- `pre_flatten_boundary_vertex_and_cost`
- `flatten_boundary_vertex_and_cost`
and commenting out the parts about parallel transport. Hope I don't miss anything.

**Comment by sonukiller** [comment]
Thank you for the explanation. If I comment out the parts about parallel cost [from here](https://github.com/HTDerekLiu/intrinsic-simplification/blob/708bc7c77955f654d56292e4e7683d16caabfb5d/src/flatten_interior_vertex_and_cost.cpp#L189), two variable `fs_twin` and `Rij` are used in the code after that also, so shall I make Rij as unity matrix or anything else is required?

**Comment by HTDerekLiu** [comment]
Oh, I think you can comment out the part from l168 to l216 in this script. This part keeps track of the curvature transport history (stored as `T`) and uses the historical information to compute `cost` (l204-l213). `R` is the rotation needed to compute parallel transport. Since you are not using the transport cost, all the code from l168-l216 won't be needed (this also applies to other scripts such as `faltten_bopundary_vertex_and_cost`)

**Comment by sonukiller** [comment]
Thank you for the explanation. So, the cost will be `dK.sum()`, is it right?

**Comment by HTDerekLiu** [comment]
I think so :)
