### ISSUE TITLE
Coarsening the mesh with border edges creates issues 

### ISSUE THREAD

**Issue by vcazevedo** [HTDerekLiu/intrinsic-simplification#11]
Hi. First of all congrats for the awesome paper and for sharing the code with the community. I'm trying to to downsample a T-shirt mesh with the provided code and I'm not sure if this is an issue or it is a theoretical limitation of the method.  

I've made a slight modification to the multigrid code for downsampling the mesh multiple times. The input mesh is this one:

![Screenshot from 2023-12-07 13-43-46](https://github.com/HTDerekLiu/intrinsic-simplification/assets/854934/4d345398-4df4-418a-82be-9b32950d160d)

Downsampling it once produces the result in the image below. The yellow outline shows which edges are border edges.
![Screenshot from 2023-12-07 13-13-16](https://github.com/HTDerekLiu/intrinsic-simplification/assets/854934/22cdc137-135f-42d7-8b62-4e592b350137)

The image below illustrate what happens If I downsample the mesh above two times (it correctly works for downsampling just once). Notice how the method is able to properly preserve the border edges on the collar of the T-tshirt, but is unable to do so for the wrist border edges.   
![Screenshot from 2023-12-07 13-12-18](https://github.com/HTDerekLiu/intrinsic-simplification/assets/854934/e3476bcf-9ce2-4176-b917-d50e79177584)

The original T-shirt mesh along with these two downsampled versions can be found here:
[example_tshirt.zip](https://github.com/HTDerekLiu/intrinsic-simplification/files/13600397/example_tshirt.zip)

The code that I've used for prolongation is very simple modification of the multigrid coarsening:
    
    MatrixXd VO;
    MatrixXi F, FO;
    {
        igl::read_triangle_mesh(filename, VO, FO);
    }

    // Initialize intrinsic information
    MatrixXi G;    // glue map
    MatrixXd l;    // edge lengths
    MatrixXd A;    // angular coordinates
    MatrixXi v2fs; // vertex to faceside map
    build_intrinsic_info(VO, FO, G, l, A, v2fs);
    F = FO;

    vector<pair<MatrixXd, MatrixXi>> meshes;
    meshes.reserve(num_levels + 1);
    meshes.push_back(pair<MatrixXd, MatrixXi>(VO, FO));

    for(int i = 1; i <= num_levels; i++) {
        VO = meshes.back().first;
        FO = meshes.back().second;
        F = FO;
        int num_coarse_vertices = VO.rows() * downsampling_factor;
        
        MatrixXd BC;
        vector<vector<int>> F2V;
        cout << "Number of original vertices " << VO.rows() << "." << endl;
        coarsen_mesh(VO.rows() - num_coarse_vertices, weight, F, G, l, A, v2fs, BC, F2V);
        cout << "Number of coarse vertices " << num_coarse_vertices << "." << endl;
        
        // removed unreferenced vertices
        map<int, int> IMV, IMF;
        VectorXi vIdx, fIdx;
        remove_unreferenced_intrinsic(F, G, l, A, v2fs, F2V, IMV, IMF, vIdx, fIdx);
        
        // create a slice of the original vertices 
        MatrixXd V;
        igl::slice(VO, vIdx, 1, V);

        // get prolongation
        SparseMatrix<double> P;
        get_prolongation(F, BC, F2V, IMV, P);

Any thoughts about this?

**Comment by HTDerekLiu** [comment]
I am not exactly sure what is the issue without running the code. But it looks like an index bug to me? It is possible that you need to nest the `vIdx` after `remove_unreferenced_intrinsic `. Specifically, 
```
(in python notation)
V_lv1 = V_input[vIdx_lv1,:] # vIdx_lv1 is the output from remove_unreferenced_intrinsic when you do the first coarsening
V_lv2 = V_lv1[vIdx_lv2,:] # vIdx_lv1 is the output from remove_unreferenced_intrinsic when you do the second coarsening
...
```
So if you are using indices to find those vertices, you may need to be careful this nested relationship.

**Comment by vcazevedo** [comment]
Hey thanks for the quick reply!

Not sure if that's the problem though. I've ran the code again with a different coarsening factor (0.4) between levels (for the post above I've ran with downsampling_factor = 0.25), and this worked:

![image](https://github.com/HTDerekLiu/intrinsic-simplification/assets/854934/4fcc20b8-568a-4c87-ac06-6944745bb7d2)

I also tried recomputing the indices from the previous level, with no success. It seems that it's not an issue with indexing. I've also observed that when the border edges represent a closed loop with only 2 triangles, things start to break down. 

The full code is below. The example mesh is attached on the previous post. 

    #include "polyscope/curve_network.h"
    #include "polyscope/point_cloud.h"
    #include "polyscope/polyscope.h"
    #include "polyscope/surface_mesh.h"
    #include "args/args.hxx"
    
    #include <igl/read_triangle_mesh.h>
    #include <igl/cotmatrix_intrinsic.h>
    #include <igl/massmatrix_intrinsic.h>
    #include <igl/write_triangle_mesh.h>
    
    #include <Eigen/Core>
    #include <Eigen/Dense>
    #include <Eigen/Sparse>
    
    #include <build_intrinsic_info.h>
    #include <chrono>
    #include <coarsen_mesh.h>
    #include <get_barycentric_points.h>
    #include <remove_unreferenced_intrinsic.h>
    #include <get_prolongation.h>
    #include <save_matrix.h>
    #include <connected_components.h>
    
    int main(int argc, char* argv[]) {
        using namespace Eigen;
        using namespace std;
        using namespace global_variables;
        using namespace std::chrono;
    
        // Configure the argument parser
        args::ArgumentParser parser("Export Prolongation");
        args::Positional<std::string> filename_arg(parser, "mesh",
                                                  "Mesh to be coarsened. (default='../../meshes/spot.obj')");
        
        args::Positional<int> num_levels_arg(parser, "n_levels",
                                                    "Number of levels to downsample. (default='3')");
        
        args::Positional<int> downsampling_factor_arg(parser, "downsampling_factor",
                                                    "Downsampling factor applied after coarsening the mesh. (default='0.25')");
         
        args::ValueFlag<std::string> obj_path_arg(parser, "obj_path",
                                          "File to save objs. If not set, coarser objs are not saved", {'o',"obj_path"});
    
        // Parse args
        try {
            parser.ParseCLI(argc, argv);
        } catch (args::Help) {
            std::cout << parser;
            return 0;
        } catch (const args::ParseError& e) {
            std::cerr << e.what() << std::endl;
            std::cerr << parser;
            return 1;
        }
    
        std::string filename = filename_arg ? args::get(filename_arg) : "../../meshes/spot.obj";
        int num_levels = num_levels_arg ? args::get(num_levels_arg) : 3;
        double downsampling_factor = downsampling_factor_arg ? args::get(downsampling_factor_arg) : 0.4;
        double weight = 0;
    
        // load mesh
        MatrixXd VO;
        MatrixXi F, FO;
        {
            igl::read_triangle_mesh(filename, VO, FO);
        }
    
        // Initialize intrinsic information
        MatrixXi G;    // glue map
        MatrixXd l;    // edge lengths
        MatrixXd A;    // angular coordinates
        MatrixXi v2fs; // vertex to faceside map
        build_intrinsic_info(VO, FO, G, l, A, v2fs);
        F = FO;
    
        vector<pair<MatrixXd, MatrixXi>> meshes;
        meshes.reserve(num_levels + 1);
        meshes.push_back(pair<MatrixXd, MatrixXi>(VO, FO));

        for(int i = 1; i <= num_levels; i++) {
            MatrixXd V_prev = meshes.back().first;
            int num_coarse_vertices = V_prev.rows() * downsampling_factor;
            
            MatrixXd BC;
            vector<vector<int>> F2V;
            cout << "Number of original vertices " << V_prev.rows() << "." << endl;
            coarsen_mesh(V_prev.rows() - num_coarse_vertices, weight, F, G, l, A, v2fs, BC, F2V);
            cout << "Number of coarse vertices " << num_coarse_vertices << "." << endl;
            
            // removed unreferenced vertices
            map<int, int> IMV, IMF;
            VectorXi vIdx, fIdx;
            remove_unreferenced_intrinsic(F, G, l, A, v2fs, F2V, IMV, IMF, vIdx, fIdx);
    
            // create a slice of the original vertices 
            MatrixXd V;
            igl::slice(V_prev, vIdx, 1, V);
    
            // get prolongation
            SparseMatrix<double> P;
            get_prolongation(F, BC, F2V, IMV, P);
    
            if(obj_path_arg) {
                std::string path = args::get(obj_path_arg) + "_" + std::to_string(i) + ".obj";
                cout << "Saving obj to " << path;
                igl::write_triangle_mesh(path, V, F);
            }
    
            meshes.push_back(pair<MatrixXd, MatrixXi>(V, F));
        }
      
    }

**Comment by HTDerekLiu** [comment]
Glad to see that your fix worked. Forming a closed loop with by two triangles (or even a single triangle) is expected when you do a very aggressive coarsening because we allow all the self-edges and their variants to appear (see Sec.4 - special cases).

**Comment by vcazevedo** [comment]
So more aggressive downsampling factors are not supposed to work? I thought that, for the case I've sent, it would still work since it seems that the coarsest model would still have enough vertices to model border edges of the sleeves. Is there an option to tag edges that shouldn't be removed during the coarsening?

Thanks!

**Comment by HTDerekLiu** [comment]
A more aggressive downsampling should work. I just took your tshirt mesh and coarsen it down to 123 vertices (visually looks like the resolution you showed earlier) and I obtained this. I guess this is reasonable right? 

<img width="628" alt="Screenshot 2023-12-12 at 3 04 01 PM" src="https://github.com/HTDerekLiu/intrinsic-simplification/assets/32198009/1ef899c2-6f57-4af6-bdf3-d9ea374803d8">

As those vertices (yellow dots) are on the boundary, I used `is_boundary_vertex(G,v2fs,v)` to extract all vertices that are on the boundary. Hope this help.

Re: Is there an option to tag edges that shouldn't be removed during the coarsening?
Haha I haven't pushed this part. I will add this functionality next week.

**Comment by HTDerekLiu** [comment]
ohh but if you need to be able to constrain vertices immediately, you will be able to do this by adding something like this
```
if (constrained_vertices_set.find(v) != constrained_vertices_set.end()) // if yes
            continue; // skip this vertex
```
in the coarsen_mesh.cpp
