### ISSUE TITLE
Preserve topology

### ISSUE THREAD

**Issue by luongthecong123** [HTDerekLiu/intrinsic-simplification#14]
Hi, thanks for the great work.

Is it possible to adjust your algorithm to preserve topology of object ?
I tried a watertight, manifold mesh, after decimated to 500 vertices, some small area on the fingers are collapsed from a cylinder into a plane. (raw mesh is in the zip file).
Thank you in advance.

[50027.zip](https://github.com/user-attachments/files/15897523/50027.zip)

**Comment by HTDerekLiu** [comment]
Hi, 

I believe the case of collapsing cylinder to a plane is just an issue of misleading (extrinsic) visualization when you have self-edges or self-faces, like the attached example. Under the hood, the mesh topology is still preserved. 

<img width="133" alt="Screenshot 2024-06-20 at 6 01 11 PM" src="https://github.com/HTDerekLiu/intrinsic-simplification/assets/32198009/012b59bd-a79d-4890-a732-460da63fbabe">

**Comment by luongthecong123** [comment]
Hi,
From your answer, I assume that you meant the raw mesh I sent is not perfect and that it has defects such as self-edges and self-faces. However, I find that the raw mesh I attached is pretty perfect. Could you please make your answer clearer ?

For the context of what I'm trying to do. First, I planned to use your algo to get the base mesh which still preserve small details, then subdivide it and fit it back to the raw mesh (or just simple projection since base mesh quality is already high) to have a semi-regular mesh. However, the thing that prevented me from doing this is the collapse of the fingers which would make fitting/projecting lose a lot of fine details information.

**Comment by luongthecong123** [comment]
This is a screen shot of the results when decimated to 500 vertices.
![image](https://github.com/HTDerekLiu/intrinsic-simplification/assets/83866371/be37bedd-3e65-4768-8333-af848850902f)

**Comment by HTDerekLiu** [comment]
Yep, this looks like self-edges to me. Since the output is an intrinsic triangulation, I would recommend to use the example code in `03_visualization` to correctly visualize the triangulation to avoid confusion.

**Comment by luongthecong123** [comment]
Really interesting work using intrinsic triangulation. Thank you for your patient and timely response !
I wonder you know any methods to convert from intrinsic triangulation into extrinsic (normal, straight edge) triangles using mid-point subdivision ? It would create really high quality semi-regular meshes, I would like to use them as input to my mesh transformer.

**Comment by HTDerekLiu** [comment]
Unfortunately, this problem is not trivial. Even if you use mid point subdiv, you can only get an approximation. 

If you don't do any simplification, you can solve this problem with [common subdivision](https://geometry-central.net/surface/intrinsic_triangulations/common_subdivision/). But once you start to remove vertices, this becomes challenging.
