### ISSUE TITLE
Assertion failed error with my personal model

### ISSUE THREAD

**Issue by LeFou-k** [HTDerekLiu/intrinsic-simplification#2]
Hi, I read your paper from siggraph 2023 and I am very interested in your work. So I ran your program but some test cases failed with the following assertion:

Assertion failed: is_same_face_side(twin(G,fs_twin), GHOST_FACE_SIDE), file D:\intrinsic-simplification\src\flatten_boundary_vertex_and_cost.cpp, line 208

I wonder if this assertion is the requirement of the following steps or this is just my personal model's error?
Thanks a lot!

**Comment by MarkGillespie** [comment]
The following steps assume that this assertion is true. Would you mind sharing the model/test cases that you're using?

**Comment by LeFou-k** [comment]
I read your apply to this issue #3 and the program work after remeshing. Thanks a lot!

**Comment by hongbin-y** [comment]
@LeFou-k , Can i ask how did you remeshing mesh ? Can you keep uv info?
