### ISSUE TITLE
Assertion failed: is_one_ring_fs_valid(F,G,v2fs,v_flatten)

### ISSUE THREAD

**Issue by hongbin-y** [HTDerekLiu/intrinsic-simplification#3]
Hello,  I read your paper from siggraph 2023 and it is an amzing project for me. So I ran your program but some test cases failed with the following assertion:
![image](https://github.com/HTDerekLiu/intrinsic-simplification/assets/31581382/7e81238c-9a86-4e6c-873d-17496240c21a)
This is the .obj file:
[House.zip](https://github.com/HTDerekLiu/intrinsic-simplification/files/12333445/House.zip)
Thanks for your tips!

**Comment by MarkGillespie** [comment]
In our algorithm, we assume that the input mesh is manifold and oriented (as defined e.g. in section 2.1 of [these notes](https://nmwsharp.com/media/papers/int-tri-course/int_tri_course.pdf)). It looks like your model is not a manifold mesh. I've added some checks to our code to emit warning messages on such inputs, but you'll have to do some preprocessing to make your meshes manifold and oriented if you want to use our simplification scheme
