### ISSUE TITLE
Restrictions on the input mesh

### ISSUE THREAD

**Issue by sonukiller** [HTDerekLiu/intrinsic-simplification#5]
Can you please tell me what are the requirements of the input mesh? like it should be watertight, manifold, triangular, etc.

**Comment by HTDerekLiu** [comment]
The input should be a manifold triangle mesh, doesn't need to be watertight.

**Comment by sonukiller** [comment]
Thank you! I tried it on non triangular manifold mesh and it is still working!

**Comment by HTDerekLiu** [comment]
I am surprised that it is working. However, I hope to remind you that the code is writing under the assumption of manifold triangle meshes. Thus even if it is “working” (didn’t output any error), I would still be cautious, you may be encountering a runtime error. 

-Derek
