### ISSUE TITLE
Mesh simplification algorithm

### ISSUE THREAD

**Issue by sonukiller** [HTDerekLiu/intrinsic-simplification#6]
I am not that good at mesh simplification concepts, my aim is just to simplify the given mesh. You have done great work and also provided the 7 functionalities. I have used 00_coarsening for mesh simplification, but I am confused with others, whether to use them for mesh simplification or not...mainly 01, 04, 05, and 06. Can you please tell me (in the context of only mesh simplification) which one to go for?

**Comment by HTDerekLiu** [comment]
If you just want to simplify the mesh, then 00 would be the example implementation. The other ones provide more features when you want to do computations on the simplified mesh, which is what the method was designed for.
