### ISSUE TITLE
Blender vs MeshLab

### ISSUE THREAD

**Issue by sonukiller** [HTDerekLiu/intrinsic-simplification#7]
I tried to run the 00 algorithm on meshes with high vertices (>200K). I first opened the mesh in Blender, exported it, and ran the 00 algorithm on it and it was working! I repeated the same procedure using Meshlab and the algorithm was not working.

I tried this experiment on some other meshes with high vertices (>200K) and the same thing was happening! Then I tried with meshes with fewer vertices (<10K) and the 00 algorithm was working fine for both Blender and Meshlab exports!

Do you know the reason? Both the meshes (exported using Blender and Meshlab) are identical!

**Comment by HTDerekLiu** [comment]
It is indeed weird. I guess it may be caused by some mesh IO issues, such as the `read_triangle_mesh` function. Could you send me the two meshes (a working one and a non-working one) for me to see what is the difference?

**Comment by sonukiller** [comment]
I figured it out, when exporting using blender it is removing the unreferenced vertices, which was causing the trouble!
