### ISSUE TITLE
always flip to ear error

### ISSUE THREAD

**Issue by sonukiller** [HTDerekLiu/intrinsic-simplification#8]
I am getting this error:
what():  [Error] failed to flip to ear in always_flip_to_ear

Can you please tell me what pre-processing is required for the input mesh?

**Comment by HTDerekLiu** [comment]
There is a chance that the input mesh might not be a manifold mesh. 
You could run a quick test using `igl::is_edge_manifold` and `igl::is_vertex_manifold` in libigl to see whether your mesh is manifold.

**Comment by sonukiller** [comment]
I checked it, and the input mesh is manifold (both edge and vertex), orientable, and triangular! In the warning, it was showing that the cosine inequality was not satisfied.

**Comment by HTDerekLiu** [comment]
Triangle inequality was not satisfied is possible. This was caused by the issue mentioned in the Sec 3.2 of http://www.multires.caltech.edu/pubs/ConfEquiv.pdf (which is a subroutine of our method). Is it possible that you could share the mesh and we can inspect what's going on?

**Comment by sonukiller** [comment]
Sorry but I can't provide the model. I think the problem is when the algorithm is checking for "is_diamond_convex" in always_flip_to_ear.cpp. In the mentioned pdf Sec 3.2, they told that the "problem is simply fixed by flipping or alternatively subdividing the edges opposite the straight angles". If you can include this cleaning method in the current algorithm, it will be great, if not can you give me any suggestions on how to implement this?

**Comment by HTDerekLiu** [comment]
We do provide functionalities to flip edges. To get a set of half-edges opposite to a vertex, I believe you can implement it via a mixture of `vertex_one_ring_face_sides` (to extract outgoing half-edges) and `next` (to extract the opposite half-edge). Then you can check whether that those local flaps violate the criteria you hope to obtain, if yes, then you can simply to `flip_edge` to flip it. 

Alternatively, a possible fix is to run `flip_to_delaunay` right after you load the mesh and `flip_to_delaunay_local` right after each vertex removal iteration to ensure the mesh is Delaunay.

**Comment by sonukiller** [comment]
I am getting "Segmentation fault (core dumped)" if I use `flip_to_delaunay` just after loading the mesh. (This error occurs with and without the use of optional parameters)

**Comment by HTDerekLiu** [comment]
Sorry, for some reasons, this new comment didn't send me an email reminder and I completely missed it. Is the problem resolved?
